services:
  silver-frontend:
    build: ./silver-frontend
    container_name: silver-frontend
    restart: always
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./silver-frontend:/app
    command: ["sh", "-c", "npm i && npm run dev -- --host 0.0.0.0"]
    depends_on:
      - silver-backend
    networks:
      - mynet
    tty: true

  silver-database:
    image: postgres:15
    container_name: silver-database
    restart: always
    env_file: .env
    ports:
      - "${DB_PORT-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynet

  silver-backend:
    build:
      context: ./silver-backend
      dockerfile: Dockerfile
    container_name: silver-backend
    restart: always
    env_file: .env
    command: ["sh", "-c", "npx prisma db push && npm run seed && npm run start:dev"]
    ports:
      - "${PORT-3000}:3000"
    volumes:
      - ./silver-backend:/app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://host.docker.internal:${PORT-3000}/graphql?query=%7B__typename%7D || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      silver-database:
        condition: service_healthy
    networks:
      - mynet
    tty: true

networks:
  mynet:
    driver: bridge