services:
  silver-backend:
    build: ./silver-backend
    container_name: silver-backend
    restart: always
    env_file: ./silver-backend/.env
    command: npm run start:dev
    ports:
      - "${PORT-3000}:3000"
    volumes:
      - .:/app
    depends_on:
      silver-database:
        condition: service_healthy

  silver-database:
    image: postgres:15
    container_name: silver-database
    restart: always
    env_file: ./silver-backend/.env
    ports:
      - "${DB_PORT-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5