/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutAuthImport } from './routes/_layout/_auth'
import { Route as LayoutguestRegisterImport } from './routes/_layout/(guest)/register'
import { Route as LayoutguestLoginImport } from './routes/_layout/(guest)/login'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutguestRegisterRoute = LayoutguestRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutguestLoginRoute = LayoutguestLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(guest)/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutguestLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(guest)/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutguestRegisterImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutguestLoginRoute,
    LayoutguestRegisterRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/login",
        "/_layout/register"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout/_auth.tsx",
      "parent": "/_layout"
    },
    "/_layout/login": {
      "filePath": "_layout/(guest)/login.tsx",
      "parent": "/_layout"
    },
    "/_layout/register": {
      "filePath": "_layout/(guest)/register.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
